INSERT INTO servico (nome, classe) VALUES
('berçário','bercario'),
('trocador','trocador'),
('playground','playground'),
('estacionamento própio','estacionamento'),
('papinha','papinha'),
('música ambiente','musica'),
('banheiro p/ deficientes','ban-defi'),
('banheiro familiar','ban-fami'),
('cadeirão','cadeirao'),
('comida vegana','com-vega'),
('comida p/ lactointolerantes','com-lact'),
('comida p/ celíacas','com-celi'),
('copa','copa'),
('possibilidade de reserva','pos-rese'),
('cuidador','cuidador');

INSERT INTO usuario (nome_completo, email, senha) VALUES
('João Dutra', 'j.dutra@hotmail.com', 'joao123'),
('Zamira Duarte', 'z.duarte@gmail.com', 'zamira123'),
('Alaquias Silva', 'a.silva@outlook.com', 'silva123'),
('Herméias Souza', 'h.souza@bol.com.br', 'souza123'),
('Ronaldo Caféow', 'r.cafeow@uol.com.br', 'roooonaldinho123');

INSERT INTO estabelecimento (nome, id_usuario, data_cadastro, cep, rua, numero, complemento, bairro, cidade, estado) VALUES
('Restaurante Fogão de Minas', 1, '2017-07-11', '79010-001', 'Av. Cel. Antonino', '213', '', 'Cruzeiro', 'Campo Grande', 'MS'),
('Figueira Churrascaria', 1, '2017-12-10', '79033-005', 'Av. Cônsul Assaf Trad', '3514', '', 'Conj. Res. Mata do Jacinto', 'Campo Grande', 'MS'),
('Restaurante Lá in Casa', 2, '2017-01-09', '79021-050', 'R. Caconde', '177', '', 'Santa Fe', 'Campo Grande', 'MS'),
('Restaurante Rua da Mooca', 2, '2017-12-12', '79061-050', 'Rua da Mooca', '1460', 'Prédio', 'Mooca', 'São Paulo', 'SP'),
('Canto do Cupim', 1, '2017-12-05', '79003-027', 'Avenida Ricardo Brandão', '230', 'Prédio', 'Chácara Cachoeira', 'Campo Grande', 'MS'),
('Gaúcho Gastão', 2, '2017-12-05', '79040-040', 'Rua Dr. Zerbini', '38', 'Casa', 'Chácara Cachoeira', 'Campo Grande', 'MS'),
('Província di Salerno', 3, '2017-10-11', '30150-330', 'R. Maranhão', '18', 'Casa', 'Santa Efigênia', 'Belo Horizonte', 'MG'),
('Tradição de Minas', 4, '2016-09-03', '30730-430', 'R. Monte Líbano', '119', 'Casa', 'Padre Eustáquio', 'Belo Horizonte', 'MG'),
('Fasano', 4, '2016-04-10', '22420-000', 'Av. Vieira Souto', '80', 'Casa', 'Ipanema', 'Rio de Janeiro', 'RJ'),
('Skylab', 3, '2017-08-20', '22070-001', 'Av. Atlântica', '3264', 'Casa', 'Copacabana', 'Rio de Janeiro', 'RJ'),
('Outback Steakhouse', 1, '2017-01-23', '91340-001', 'Av. João Wallig', '1800', 'Casa', 'Iguatemi', 'Porto Alegre', 'RS'),
('Boteco Kabanas', 2, '2015-02-09', '74215-110', 'Rua Dr. Zerbini', '2693', 'Casa', 'St. Bueno', 'Goiânia', 'GO');


INSERT INTO estabelecimento_foto (id_est, url_imagem, data_cadastro) VALUES
(01, 'foto-estabelecimento-1.png', '2017-05-08'),
(01, 'foto-estabelecimento-2.png', '2017-06-06'),
(02, 'foto-estabelecimento-3.png', '2017-07-11'),
(03, 'foto-estabelecimento-4.png', '2017-10-16'),
(04, 'foto-estabelecimento-1.png', '2017-06-08'),
(05, 'foto-estabelecimento-2.png', '2017-10-07'),
(06, 'foto-estabelecimento-4.png', '2017-02-24'),
(07, 'foto-estabelecimento-4.png', '2017-10-27'),
(08, 'foto-estabelecimento-4.png', '2017-08-15'),
(09, 'foto-estabelecimento-3.png', '2017-11-20'),
(10, 'foto-estabelecimento-1.png', '2017-08-08'),
(11, 'foto-estabelecimento-1.png', '2017-07-04'),
(12, 'foto-estabelecimento-1.png', '2017-06-10');

<<<<<<< HEAD
=======
INSERT INTO avaliacao (id_est, id_usu, descricao) VALUES 
(12, 5, 'cenospecies gonochorismus coltskin Cyclophorus Causus contumacious exacerbescent glimmery annelid Daphnean fermentescible cystidean astronomically aphidid calcigenous diametrally estimator cashmere irascibly Batocrinidae barosmin attainture footmaker Iliadize'),
(12, 5, 'bemuck crumblement artificialize cytopathologically Bimbisara brachiation guptavidya countryward extense glycolipide comminutor conepate circumocular cachexy geographize gawm helminthologic Blenniidae geologically enlacement bailor headful genetrix catalase'),
(4, 3, 'inabordable hackmatack heterographic becquerelite clock cryptous condignity ecuelling Dasylirion chromatophilic antimonarchial eutectoid gemmy agentess coadministratrix belzebuth holdable gastroenterocolitis bluetongue accidentalist allegorization interradiate fulgurator Freycinetia'),
(3, 4, 'claim dubiously futility Actipylea ingeneration antistreptococcic homotransplant eclipsation gease dinornithic cephalocathartic capshore chemicalize huckmuck glycolysis equinely infragular execution egalitarianism brickleness conveyancing chilognath berth abroad'),
(11, 2, 'dupedom encowl declivate egregiously dithematic feued Irredentist guaiol dorsiparous conquering emanative adenocarcinomatous edeomania halophyte greggle cashierment cocuswood gliderport Dasiphora concertina gypsyhood Gualaca Bardesanism homoeotype'),
(3, 1, 'innermost Ati Ectotrophi hideland halibiu hylomorphism impregnable hemimellitene demographically illiberalness duodenal interlibel beginner ammotherapy birthstone aye demijambe Catocala hexosemonophosphoric assentor cyanide inevasible educationist illustration'),
(4, 1, 'damnatory Ceratites hypolimnion alabastrine empathize anisilic cruce ampery fortune Dactyl anastaltic horologer inflate coessential acetanilid coelectron beechwoods Ecca dietist fadedness campylometer grower declensional ethnical'),
(2, 4, 'hemoflagellate cocoonery exceptious Hamamelidaceae Diplospondyli carotenoid deflationary goondie gloss antler biasteric californium giganticidal halloysite Elaphrium ethnically calcaneonavicular inhospitable carpophyll fissileness gloom debilitate Geissorhiza hyetological'),
(2, 2, 'grandmotherism amethystine glossist flange interspheral infestment cucullus discoverable gloryless Hitoshi intempestivity hypocotylous helicon anaretical fibroadipose Eupatorium colonization appose inartisticality fisticuffery catastrophic brominism belonite endosmotically'),
(8, 5, 'bemail bouncer horizontalize attributer carol cryoscopy ilesite azide dodgy introactive actinotherapeutic endothoracic Finnic gain iracund albuminometer finestiller bescramble illocality forweend inspiriter foolproofness cratometer collationer'),
(10, 2, 'butene Hermo howish insecurely aleft elbowboard Dicentra fewterer calcareoargillaceous Fram bridling Encrinidae alisphenoid electropathy consertal crantara agglutinant interzooecial aureation dianite betassel exogenetic forbid fluoranthene'),
(7, 3, 'intellectualization icterohematuria iridoparalysis hippophagist golem inogenesis Clathrina Augean chirological Beroe antistatist hydrops excretes anencephalotrophia inwork continuousness dandiacal ecderon emissivity falciform acerate heiferhood dealation hakdar'),
(6, 1, 'incontrollably implicately iridioplatinum curtaining crawfish enlivening healable hydremia absolute cracky cubica Hebrewdom chinamania Athens biorgan fellingbird Antonia exclaiming bemean bromethyl fourrier homoeochronous circumvolution excusably'),
(11, 4, 'dolcian Crotaphytus depolishing hypophysectomize grabble gavialoid disarticulate cryosel exiguously casula coetaneity cordant esquamate Eben dangler imperceiverant incombustibleness cubically electragist antichloristic dextrinase Dadu endorse adiposuria'),
(5, 1, 'alemite dissimulative empanelment friggle inreality academicism chromatone arthredema dentated choraleon convertism indifferentism Brythonic booky batrachian intently inchworm althorn geodesist flouting aguilawood evincement gravelike ciminite'),
(5, 1, 'diadelphian antifederalist autumnal assistance biostatic benedictively Berkeleyite cablegram Gobelin fissiped aeonial Arctoidea far brakemaker chagul dialkylamine enoil dodecahydrated bridgemaster hendiadys gosh hyposynergia guessingly dysuric'),
(4, 3, 'compassionateness epigastric asteraceous Fitzclarence demise flak emptysis calendrical cauliflorous alcoholmetric hereditarily arthragra carlot flexuous criss fulciform coassessor chichipate fishwoman Della ajivika apperceive inflamedly delightable'),
(10, 4, 'Casziel interzone Celia homeowner annulus hysteria fide accumulable cerebromedullary cacorhythmic autocremation fenestra irresonant Cyclostoma gunge auxesis indiscriminative cancan calyptriform confinable dupery hematoplast appreciatory deceitful'),
(12, 4, 'airliner cervicobregmatic intimacy coppersmithing bifurcate dilutent irritate afterbreach Falcones annexationist goosishness choosable educive inane acclamator barytophyllite formally impressionably archegonial baboonery forepart cynomoriaceous enclitic ecmnesia'),
(2, 5, 'adventureful Ismailian compilatory cardiospasm dependingly Cestrian fattiness infraocular benchfellow glideness bootyless exosmosis grunting elotillo imperceiverant fellmongery groundneedle cabocle fold eastmost hypotenusal impassableness Crotalidae belga'),
(6, 4, 'isographically Comptonia featherpate frightening halfbeak expiscator homochromatic conspicuity Bishareen durian chaetopod clogdogdo encephalocoele easement alytarch Euclideanism beribanded diuresis Abitibi blackberry electron bughead dreamtide fossilogist'),
(3, 1, 'expand incapaciousness horbachite floricin aggressor aprioristic indoors Doedicurus colluder clomben bene heterogenist dolichocephalism Greekless enteromesenteric Canna footstool adiathetic cedry Gastraeadae animated aerification amyloplastid how'),
(8, 3, 'characinid herbarism Droschken Ichthyosauria eupyrene imbecility hexacid ectoblast barristership cudava circumcircle hauld bescutcheon adviser colorimetrics Hunterian Aesopian attendment embedment chromogen Iacchic funnily dyspituitarism domesticative'),
(2, 3, 'anatomicomedical illusor Exoascus hylotheism amphimacer Chrosperma feodatory Heliornithes coalitional astrophysics gastrojejunostomy finished Cat inimicalness erethistic behear crunchiness aerolitics groundedness conicality forsterite clubwood alary fisting'),
(12, 1, 'Comanchean agone Amsterdamer ciliolum inhabitedness gauging interpolary androkinin adipoma elderberry cub hexagonous bilabiate answerability deficience dissatisfaction importance balachong assigner archegone Agau hillman ecanda duledge'),
(1, 1, 'dowdyish Heraclidae agrologically eudidymite Bacillaceae anabranch colloquize intraclitelline contradictiveness candelabra casal albatross insensibilize Crete inelasticate Aquila galloping borderless casemented affectionately coadjustment czarinian dapperling Bruce'),
(3, 2, 'bilateralness foliar calipee hematocathartic balefulness bident commodate androcracy donnishness boyardom convocationist Getae Epilachna injuriousness discocarpous bullsticker intercostohumeral bimanal anteroparietal Gelechia demurringly cycloidotrope attestation bacteriotropin'),
(9, 2, 'cigarless discern holoblastically Eopaleozoic incomprehendingly estampede diminish coemploy belatedly group achenial Cete burgoyne decantation entrepot adenomyxosarcoma foreganger Antennata attestative dayblush counterprophet carapacic compatriot epichindrotic'),
(2, 2, 'boobyalla confide inessential eupraxia cornbin gatchwork interworry gratuitously antirevolutionary exit hierograph adenylic galvanoglyphy heumite ethylenic grassflower guillotinist dupery duraquara cumulite delabialization antispiritual ergotin glare'),
(2, 2, 'Antipathida Carapa coeffluent antiprime ellwand compiler Gutnish braider coinfeftment deerhorn calcareosiliceous gleaning impoliteness colegislator iliocaudal adoptive antihelminthic coadunatively hysteroid duplicate cacophonous Eurygaean dispensary feodary'),
(10, 5, 'chemicalize chenevixite damnation chloromelanite frenulum biocellate aspartyl cribwork dasycladaceous enouncement eurytomid gatewoman endysis dreadly Glagol fanaticism aniconism diadelphous expectation gynostegia Antipasch Brachycome expostulation hysterocrystalline'),
(3, 2, 'frostiness hydromyoma coburgher heartsickening barracouta balneologic discerningly encyclopediac conjugationally impassionedness depravity cobelief Czechoslovakian anthracomartian demeanor Anablepidae bejazz flopover embodiment Freddie Adam imbalance colibri extractor'),
(2, 2, 'foxily bacterize contrasuggestible attractile idiographical conferruminate deanathematize congeal arthromeric Chilopsis brachycranial Falconiformes candymaking ectally Capuan cuckoopint forewisdom contemnor copperytailed antiglyoxalase impious antherless growthless fitchew'),
(3, 4, 'bedouse calumny Aplacentaria grandstander copy buttocked colliculus antibasilican catenoid appetitional inversely compeer fortuitously antelucan aerodonetic bushlet cobreathe Ilysanthes infeftment ileocolic giornatate bulger adoptianism granulize'),
(10, 5, 'irrememberable Euglenoidina greyhound disruption dead exothermous chiropractor counite incompleteness devilfish backdrop amorosity headquarters dambrod Finn assishly dredge Arctogaeal balanid inconsecutiveness excathedral fumiferous collochemistry continuately'),
(2, 1, 'cyclorrhaphous greenside ecclesiastic checkerberry colorableness epistemolog blackguardism ektene benzoylformic asymbolia ankaramite incensation caprylene coalless fidge anticlactic argenter Isleta frigidity intraseptal degasifier Crossosoma absentation colonially'),
(11, 5, 'incavern electrometallurgy hesitating consocies dismally disgracement dubb Cercosporella behatted centroclinal impignorate detribalize Deguelia assumptious hydrodynamical antimosquito contangential autogiro compact angiotelectasia denudant grallatorial dawkin hurtlingly'),
(11, 5, 'abominable enniche Exarchic Caedmonic dynamistic impermanence ambuscade daimonic ann Branchiata gastroenteroanastomosis enclaret collectivist downfalling feldspar begrown B engrailment autosoteric arthropodan cotwin haremlik intramyocardial Genetta'),
(10, 4, 'hygienist cydippian bullpout fasces bhikshu dogtoothing chivalresque gianthood brichen brotherly hexadic conferee harlequin deperdite ectocornea autograph antarthritic buttocker Anhalonium acierage insemination footwork beautied bleariness'),
(9, 3, 'Alice Fellani coelenteron ionosphere hexameric collage codpitchings eiresione facility interbreath epimeron especialness hogshouther indelicately Hydrocorisae agmatine azygos duller interadaptation Cyprinidae heatheness ezba chroococcoid fikie'),
(8, 4, 'inurbanity carls gaslighted injudiciously exothecate interrupting confirmity hydrostat amphistomatic Bais bitbrace belzebuth cursal cogitatingly deedless huggable dory condonement Humiriaceous glaceing Coloradan exhibitionize bisulcate cautionary'),
(12, 4, 'cloddish baffle asterial causeless crepusculum forleft ani conoidically carbosilicate centetid fellifluous Finmark impressor Chinese antinegro conchoidally blaeberry exemptive hoofer fivesome enterotoxemia bindlet detrited Gyrophoraceous'),
(3, 1, 'Bannockburn Asphodelaceae hermitic Austrian albiness ammoniojarosite attritive antisideric faintish etcher emancipator brauna Dicotyledones anxiety cholerophobia curialism Gobinist Biddulphia influenza Griff borrowable choultry casaun diphase'),
(7, 3, 'intercondenser churchgoing cagework bushy digram endoesophagitis agomphious dialogistically crownlet interoceanic accustomedly degenerateness indexless drainer adscriptive indexlessness geomaly ascidiform interset hypochlorhydria bedevilment duali booklike castoff'),
(6, 5, 'dimiss hideousness coinmaker exorbitance canzon cherub archsacrificator configurational aerodynamicist ascham ceral blechnoid fastuousness cyamelide gynantherous cytode controllability crosstie endangerment calicular facsimilize cheesecutter barebone boomable'),
(7, 2, 'gaylussite coelomic cowshed briar cycloparaffin antipyic insubvertible detachment fraudful dunder Cahenslyism hollow cenogenesis injure guttering diazotic commissive fertileness desiliconization feltwork hypsicephalic fascinatress hypsilophodont discanonize'),
(4, 5, 'capture attrap Antaimerina determinant additionary infatuatedly askingly intenerate hia herpetism Austerlitz benzaldoxime flyflap community exarillate Dermatoptera continuist hydriatry casava diffused dauphiness gamogenetically basting informidable'),
(10, 3, 'historicalness discrete emplace hawsepipe fibrinogenetic Charterist Aetian invariance electrophrenic erythroclastic adenoma inabstinence aliofar ilicin gawby declaimant cerotate expunge Balawa evaporative erucin grouseward draper backsword'),
(1, 4, 'coralist Chasselas claustra heliotypic freckled ginglymodian enslavedness dorsicornu epiotic isonomous hostlerwife hoisting irreversible Canidia composedness interplea bhandar ideophone dreepiness cinchonic caveat autophagi Ioni eelpout'),
(7, 1, 'ambrology ambrotype blade generality bagmaking crabeater Armida discordant civility invigilation dower drosograph clubbed freehold herpetomonad gali Gaeldom hyperimmune declinational Brigittine Coelata apostematic cuss banago'),
(1, 2, 'hepatotoxemia darger coprophagia antiphon chacate brokenheartedness guider concessible gashliness inleague dermonosology bacillemia Galibi inopportunism hoppestere growsome borborygmic chylothorax enthusiastly convenee divagation coadnate billposting doty'),
(6, 3, 'Calyptrata Amioidei coupler Clathrina haugh foute Aloadae circumnavigation coralloid hematometer bandore attest hecte cyme benchlet Baloskion cornwallite frustrately degustation fixative babblishly alanine bap floody'),
(4, 2, 'appetible gingerbready Celtologist imbark Amsonia eventual Cyprinodontes crenotherapy cholericly arakawaite decreative fablemonger evenfall horsewood capybara Apache cockshy inheaven cacotrophia gutturopalatine albopruinose grandsonship billethead intercolumniation'),
(12, 3, 'avourneen days highball dorsocaudad extrascriptural inflative atweel indecentness gibingly cirripedial heedily honk foveolate gadget imaginary condensed crematorial dermic Arthrodonteae divinable excellently gynethusia holocephalous feldspathic'),
(7, 3, 'adenoidal antimonyl educand dislocator acerous glint enticing cupmaking enterotomy docmac Bellabella brace disbalance ebb boroughship heliozoan ceroplastic abandonment efficaciousness choralcelo hureek bisexual anticholagogue capias'),
(6, 5, 'figuratively eurybenthic anthropotomy dispersion graduality desireful intermolar cockneian exoteric hypercosmic additamentary Cephalotus dissimilate gardenly inflamer glucinium Gathic indemonstrability Aluconidae acaricide algolagnia interoperculum disherit betorcinol'),
(8, 3, 'generalty dawdlingly geoponic frostflower despiteful hostileness gusto interunion bloodless cedarware autotherapy Homoean cringe intestinovesical anthraceniferous dogboat coregnant inhume Hahnemannian believe antitax inositol amynodont doxography'),
(11, 2, 'cleanout brachysclereid dibhole augitite dodecarch daringly figging hydrargyria daemonurgist fahlore ischiopubic freck apoquinine azygomatous idiochromosome antiphlogistian dependency declarative bowfin indeposable Autosyn adiaphorite carbonimeter antique'),
(2, 1, 'ashame antehall disapostle calisthenical advisatory beheadal commandress idiorrhythmic Galcha impermanently halfpaced evolve bimillionaire dichasium ermined apickaback coltpixy hyetometer hypovitaminosis duograph cyclometry cancelable gasking hydrosalpinx'),
(4, 3, 'acrospore detar amphibiously formazyl ghoulery crepine ichthyoform expensilation gasoliner antarctically Egyptian crystallochemical exoticalness dayward homily ethanedithiol goi ambidextrous bosslet incontrollable aspergil acrobat Acrasieae Ectocarpus'),
(1, 4, 'benedicite foretop Dwamish bohemium Cursa gruffness inwind hoodlumize epacme amatrice hysterosis Dishley crownwort Cohen deflectometer guardant behatted arthropterous curietherapy covenantal electionary clavial human augurous'),
(2, 4, 'endorsement bradsot cevadilline chantry Hydrophis empall Camisard abolishment hoplomachos Compsoa ensuer expositor disenmesh dryness adenomatous again ductilize deltoid hagtaper fifteenfold impermeabilize god indissipable goniometrical'),
(5, 1, 'engraver Heraclitean clobber feelingless curculionist blemisher aristotype dorsicornu antecede continuate delphinin ankyloproctia gastrotheca anal dispeace bobsleigh exomphalous calaber afterhold cylindrically dulia credulously blepharemphysema academize'),
(3, 1, 'inaffectation drudgism gizzard bondsman havoc autosensitization dool coerciveness discriminately deprivable archegonium chemiatric ambiguousness emplastration deceptive adzer bedcase archseducer hypomnematic Dubhgall caner capful isomery amphiphloic'),
(9, 3, 'argyrose fluidally hersed ectasia hatbrush benzoglyoxaline acknowledger abjuration hymnless forecovert chrysopoetic chelys demikindred homily Christocentric creedal euphonous energumenon cypriniform galegine hetterly comfrey blunger congelifraction'),
(1, 2, 'codworm biguttulate butanal euonymy creosote geneat beavery advocator albumen facture gyrencephalate agla Bristol frolic growed inassuageable entreatment Assyroid bigot alliterationist dentilabial calycifloral Delawarean gluish'),
(11, 1, 'decadrachma creaturehood Geryonia handshake calcific chelide aminization cockneian cobridgehead irresonance hyalinosis branchiogenous halolike chalcolithic challengingly Antinous fustigatory congruence biogeography disaffirmation diphosphoric drawer forevow Caerphilly'),
(12, 4, 'farrierlike croucher implete entach decatyl gynecologic Adaize hematocystis Buninahua ataxiagram contraindicative invariantively comfortingly flog Arctocephalus grylli cazimi evidentness caffeone countertype enturret aesculaceous edema arithmometer'),
(7, 1, 'godlessly halse disguisement blindfoldedness coparceny inkstandish Cordylanthus electrowin ammonitic human Belone Echinozoa balas diarthrosis barristership aftersong croaky dephlogistication epicerebral gens Churoya drightin cephalochordal ejective'),
(11, 5, 'consistory braccate desmidiaceous dimity amusement burgensic babingtonite chattel extrasterile Gymnodontes flatweed exoperidium cerebroparietal distortional aranga artificialness inglenook cheiropatagium heterophemize cyclide cookless illuminatus castrametation cerrero'),
(10, 1, 'extracurriculum crinated Hylocichla bitstone formwork deutomalar contributorial hematoscope complainant dinmont awkwardly cremaster decaesarize casease ballywack Corrodentia calefactory infraprotein emphyteusis esclavage auxiliar dairying amblygonite feudalize'),
(8, 5, 'guaiacum bibliomanianism coarctation estruation combflower intermixtly accolated centrifugate inappreciative educatory Grecize agnate anyways agrah androgyne angelique Emballonuridae calcaneoastragaloid hypoaminoacidemia hyperexcitability Dimittis curtilage infectiveness epiphyseolysis'),
(9, 5, 'estacade berthing hypsibrachycephalism chandi bollworm Bryanism floodless flatly figwort dun geomorphy gloriously furfuraceous cracking gratulation coyure abasedly cutthroat imperviability either architis discerptible Actiniaria clotter'),
(3, 1, 'honoree forgot degreaser deglutitious clogginess branchiosaurian dermonosology humiliatingly divertingly Atheriogaea clabber companionway defiled hoblike counterideal federalization bespout bunghole fusion fucus belduque haloesque ache arterially'),
(8, 2, 'dokhma examiningly demitrain Cajanus clavilux burrgrailer inburst hypolydian excitant intercommunicability decarbonate capitelliform bewildered ambalam demijohn Almoravides chalcid hortatorily corespect bankside cotraitor archleader antiroyalist insipidly'),
(3, 1, 'agreeability battologize aghast acrospire Comid grapewort gruntling intraseminal bodiced endorser atropinize chancroidal baster forbathe indiscerptibility aegithognathism denaturalize faraway eloge alish herohead doorsill gerbe falconer'),
(2, 2, 'demicylindrical Idotheidae hereunto immolate actify humblebee cryptopapist confederacy hippurite indyl burlap amotus chattelism interrogatorily hyperapophysial gentlewomanhood coinage basilical hexaplaric grainy carcinological grouped androphagous enactable'),
(1, 1, 'dangerful footroom actuaryship interbranchial irrevocably hoick institorial are innovant chondromucoid dryth esotropic Celadon aetheogamous aliturgic carcinosis executant dreadingly growth electrotherapeutic framableness embracery egophonic Coquille'),
(7, 3, 'furlough ethene agonizer cockmaster hogan coevally cogracious feudovassalism emotionalism brownwort Dane hypaxial criminosis curblike bathyhyperesthesia Germanify aerotactic fiendliness heterogenean isochasmic Bononian fellowship bedragglement fencible'),
(7, 2, 'headborough Berossos hydrosorbic baiocchi immi cointer borowolframic hypophosphorous auxiliarly bediademed bracingly Euonymus excorticate arterial equilibrium anciency ablative codicil Hibbertia gurgoyle idiomorphic gnawn hoyman elabrate'),
(12, 4, 'getting choragium intercostally duckhood antedawn eucrite breakable benevolist disinherit geochemist garniec fund dextrosinistrally hematomyelia disencumbrance insimplicity aphrosiderite aptychus exiguousness feracity courter gamete cider hemocoelom'),
(12, 4, 'Cretaceous Clavicornes beehouse insecurity gradefinder dermatoma blazing doctrinarian bequeathable ardoise endopathic enantiopathic comfortingly infuriation chevronel astrochemist diffuse copeman Borocaine cheeper crossweed diagrammitically amphispermous Aramaism'),
(12, 1, 'Constantinian aerostation deevey bountifully acetimeter infrastructure cursorily beglide infidelly Delphinoidea implement Doliidae delightingly binauricular docker caulome infectiously binbashi Fucales archetypically allicholly chromatophobia effortlessly clivers'),
(4, 3, 'clinkery boulter baseman alloplasmatic ineludibly apyretic gypsophily enlighteningly antirealism insincerity gastraeum Fionnuala infancy circumstantiation isocyclic hospitage Helenium canellaceous houppelande befrill bacteriuria icehouse Amerind connive'),
(4, 3, 'despect abnormality autoecholalia deconcentration ichneumonid caulopteris barleymow cytioderm calycophoran counterseal chasmy calcaneofibular deemster biannulate intelligent arrased dacoit byee electrophotometer Daltonist circumspectness Ferrara friarhood Dashnakist'),
(4, 5, 'inverminate besmouch creamcup Americanist acutely alpenstock formulization ensurer irrepresentable barricader ceaselessness comfortress footlicker ankus bicrofarad Cedrela bannock burden deisticalness Cacajao Arneb coccidium clave indiscreet'),
(7, 2, 'colliquate cahiz Gymnoconia epeeist hypertensin Acinetae exsufflicate erythron Garryaceae corselet incommensurately erichthus divot elbowchair habitance embryophagous Flacianism Duke confoundable galvanize Grant interempire archabomination atlatl'),
(2, 5, 'demisang fiddlestring binodal cryptically biglandular Ephemeridae fady homoiothermism impack Hadendowa Arminianize intraperitoneal hiller cowlick antepagments contemptibleness flambeau extraction flouncing cooker ethenoidal grudgefully invendibleness gantryman'),
(12, 4, 'comeliness extrinsicality equipaga coenenchymatous ceraunoscope daalder Americomania ich cymbaler beshiver consequentially berkovets ambroid gripless arillodium Carcinoscorpius butterfly exship dado dispensator Bidpai autotransfusion hypotaxic activator'),
(9, 4, 'Ebionite floggingly conquer bisinuation disillusive archichlamydeous increase Amphioxides hare hitchiness equate corymbous irritatory determinable centrodesmus entame hybodont guaiacum archsacrificator isotherombrose agitation gynocratic gunate foldable'),
(8, 4, 'fullhearted biogen bridaler brazilite acetochloral coprophyte Hippa beige flow chromite hoodcap calvaria beaconless honeyedly cotransubstantiate actinogonidiate invaginate hydrokinetical adorally chapless demonology coinsurance boob impersonable'),
(3, 3, 'dictynid inadmissible bipunctate indeformable balneophysiology grovelings balandra intratarsal hematobic adosculation finagler deflected antiloimic finery brookweed algaeological euchroic Galbulinae dirempt baseballdom brizz basketballer hircocervus eastabout'),
(8, 4, 'chiastoneury electromechanics athrill glareworm cockneyize acetifier fortunite insignificant ditchless Confed clarty cathedratica hyracodont dawtit beclout inexcusability dothideaceous illustricity claquer enfoil flusterate baculiform consigneeship greencoat'),
(5, 4, 'extratracheal bifurcation forestwards dianilid foretaste frazil Ancylopoda argentamide danglin hedonical Cocama Abrahamite calefacient fadingly goosishness candlewood gaulin bulgy formaldoxime crave horrify excarnate cramper granulocyte'),
(1, 3, 'delirifacient duad bidactylous buttermaking imbroglio extendedness conclusion inexpensively blepharoptosis anthropomorphological iridiophore dregless communital blowzy epicorolline epidermis guttula forelive feigher inalterableness Elaphomycetaceae Anagyris Biblically dermatolysis'),
(10, 3, 'ectasis diaper fruitgrower Embolomeri Algonquin artistically crosscutting Actaeon bonewort hypopepsia camarilla gastrophilism admissibly experiment Euphausia excisemanship cocowort combless gladdon deorusumduction alvite intaglio bulbotuber domiciliar'),
(3, 3, 'galactopyra goshawk cirurgian chitinogenous colpoperineoplasty coreveler barish anaclisis iconolatrous demibastion arcature hammertoe cephalochordal adfluxion Althaea cashaw chalcites axillar azurine cerebroscope celiocentesis demibeast habiliment biprism'),
(11, 4, 'calendarial Hamites dissympathy celestite anticonscription countship covariant frolicky cryolite hormos corozo angulosplenial borickite Duplicidentata dosimetry inofficious interantennary cumbent agnosticism Hawiya filmet heartsomeness Curt albuminous'),
(12, 1, 'coregonoid dabster foresight aidable clerkliness assuasive chloroformism driverless arrestor antemundane husband chorioadenoma carbolic Esperanto immovable befrocked anthroposophist crystallometry affiliation Bardolph abstention colotomy Cycadofilices Iberes'),
(3, 3, 'clitoritis fessely detacher enheritage deobstruct canicola cardinalship belting beknow aionial geocratic exorcisory anorectous exequy hircosity batter importable gloea Dolicholus accelerative disenslave celiadelphus coniferous garthman');


INSERT INTO avaliacao_servico (id_ava, id_ser, pontuacao) VALUES 
(23, 3, 3),
(88, 15, 1),
(91, 8, 4),
(1, 15, 1),
(42, 4, 5),
(87, 4, 1),
(26, 8, 1),
(3, 15, 3),
(42, 15, 2),
(61, 5, 4),
(83, 10, 4),
(55, 2, 1),
(68, 8, 3),
(5, 4, 3),
(28, 12, 3),
(30, 9, 3),
(60, 11, 5),
(93, 1, 3),
(29, 11, 2),
(59, 1, 2),
(39, 1, 3),
(30, 14, 3),
(22, 6, 3),
(18, 11, 1),
(88, 7, 4),
(64, 3, 1),
(45, 9, 5),
(56, 6, 5),
(54, 2, 1),
(79, 15, 3),
(27, 3, 2),
(60, 9, 4),
(68, 1, 5),
(25, 10, 1),
(64, 3, 2),
(17, 13, 1),
(84, 13, 3),
(48, 4, 5),
(20, 4, 3),
(85, 6, 4),
(71, 12, 5),
(90, 2, 4),
(24, 11, 1),
(15, 6, 1),
(47, 6, 2),
(51, 6, 4),
(33, 14, 2),
(58, 2, 5),
(52, 15, 4),
(74, 6, 4),
(49, 7, 4),
(59, 5, 4),
(27, 3, 5),
(62, 6, 5),
(26, 10, 1),
(4, 10, 5),
(77, 6, 2),
(67, 1, 5),
(55, 11, 5),
(46, 15, 4),
(7, 14, 5),
(47, 12, 4),
(23, 4, 4),
(81, 9, 5),
(89, 6, 3),
(41, 14, 2),
(47, 5, 2),
(6, 9, 1),
(38, 6, 3),
(19, 9, 3),
(13, 15, 2),
(16, 3, 1),
(10, 1, 5),
(80, 10, 3),
(9, 4, 3),
(67, 1, 2),
(22, 6, 4),
(77, 11, 1),
(86, 7, 5),
(35, 12, 5),
(14, 12, 4),
(17, 8, 5),
(99, 5, 1),
(37, 15, 3),
(80, 10, 1),
(92, 13, 4),
(38, 3, 3),
(5, 3, 4),
(42, 7, 1),
(32, 10, 4),
(11, 6, 2),
(56, 15, 2),
(63, 3, 3),
(18, 4, 3),
(85, 13, 2),
(33, 12, 2),
(30, 8, 2),
(80, 12, 3),
(1, 2, 3),
(68, 5, 1),
(72, 3, 2),
(84, 5, 3),
(11, 7, 2),
(41, 9, 3),
(91, 15, 1),
(1, 1, 3),
(12, 2, 2),
(90, 4, 5),
(55, 4, 1),
(85, 3, 5),
(30, 6, 3),
(68, 14, 5),
(15, 14, 5),
(66, 11, 1),
(98, 14, 2),
(22, 12, 2),
(11, 2, 3),
(42, 11, 5),
(42, 11, 1),
(54, 9, 4),
(58, 11, 4),
(5, 4, 3),
(80, 9, 3),
(95, 4, 1),
(74, 3, 1),
(59, 10, 4),
(48, 11, 5),
(89, 3, 3),
(82, 13, 4),
(46, 5, 4),
(69, 14, 1),
(80, 11, 4),
(19, 3, 2),
(69, 7, 5),
(48, 6, 5),
(41, 3, 4),
(83, 11, 5),
(37, 12, 3),
(9, 1, 5),
(87, 15, 3),
(39, 3, 5),
(99, 4, 5),
(37, 9, 2),
(55, 15, 3),
(98, 1, 2),
(17, 2, 5),
(30, 6, 3),
(6, 4, 2),
(59, 9, 4),
(14, 5, 5),
(16, 13, 2),
(79, 15, 2),
(71, 12, 2),
(38, 3, 4),
(2, 10, 4),
(85, 11, 4),
(72, 7, 3),
(75, 4, 1),
(56, 9, 3),
(57, 7, 5),
(46, 14, 5),
(3, 11, 5),
(6, 10, 2),
(44, 8, 2),
(31, 14, 3),
(15, 8, 2),
(51, 8, 1),
(78, 9, 4),
(73, 10, 5),
(84, 8, 2),
(1, 12, 2),
(51, 2, 4),
(45, 13, 2),
(69, 15, 5),
(75, 1, 1),
(30, 14, 4),
(52, 3, 5),
(29, 4, 3),
(96, 7, 1),
(3, 13, 1),
(10, 10, 4),
(73, 9, 1),
(16, 2, 4),
(73, 14, 2),
(75, 2, 4),
(98, 6, 3),
(8, 15, 1),
(76, 6, 2),
(82, 6, 3),
(29, 9, 3),
(98, 7, 3),
(44, 3, 2),
(86, 12, 3),
(86, 6, 2),
(28, 7, 3),
(61, 1, 1),
(42, 12, 4),
(33, 14, 4),
(5, 6, 2),
(20, 6, 1),
(57, 6, 1),
(29, 7, 3),
(73, 4, 1),
(5, 9, 5),
(47, 11, 1),
(42, 13, 2),
(9, 2, 5),
(57, 10, 3),
(85, 11, 4),
(46, 7, 5),
(12, 5, 5),
(27, 8, 2),
(36, 12, 5),
(92, 7, 1),
(1, 2, 2),
(64, 8, 2),
(66, 3, 2),
(66, 3, 3),
(35, 6, 2),
(97, 9, 3),
(13, 8, 1),
(7, 7, 1),
(62, 14, 5),
(6, 4, 4),
(50, 7, 3),
(43, 8, 5),
(50, 3, 5),
(32, 5, 3),
(86, 8, 4),
(48, 7, 1),
(40, 14, 1),
(49, 8, 5),
(37, 12, 1),
(20, 11, 5),
(61, 11, 5),
(90, 13, 4),
(4, 2, 5),
(57, 6, 3),
(25, 8, 2),
(95, 13, 4),
(52, 5, 1),
(97, 10, 3),
(87, 11, 5),
(18, 12, 5),
(68, 2, 4),
(25, 5, 2),
(75, 10, 4),
(8, 6, 4),
(57, 6, 2),
(6, 7, 3),
(73, 2, 2),
(89, 13, 3),
(4, 10, 1),
(15, 4, 4),
(39, 6, 1),
(50, 9, 1),
(85, 7, 5),
(24, 12, 4),
(74, 14, 5),
(57, 7, 5),
(98, 8, 4),
(76, 15, 4),
(6, 12, 5),
(71, 8, 1),
(7, 3, 1),
(29, 12, 4),
(8, 14, 3),
(13, 2, 3),
(62, 5, 4),
(79, 15, 1),
(68, 4, 2),
(69, 15, 1),
(96, 6, 1),
(81, 6, 4),
(44, 11, 1),
(84, 7, 2),
(82, 10, 2),
(1, 1, 1),
(69, 1, 5),
(41, 7, 2),
(81, 3, 5),
(98, 4, 3),
(94, 11, 3),
(76, 5, 1),
(94, 14, 5),
(17, 5, 3),
(5, 10, 4),
(48, 4, 3),
(29, 14, 3),
(85, 13, 2),
(90, 2, 2),
(14, 9, 5),
(28, 6, 2),
(45, 8, 4),
(77, 10, 4),
(89, 1, 1),
(91, 9, 4),
(14, 7, 2),
(81, 14, 2),
(30, 8, 1),
(96, 9, 3),
(69, 12, 5),
(14, 14, 4),
(37, 5, 2),
(51, 6, 2),
(73, 9, 1),
(17, 12, 1),
(38, 4, 1),
(44, 15, 4);
INSERT INTO estabelecimento_servico (id_est, id_ser) VALUES 
(1, 2),
(2, 1),
(3, 1),
(4, 4),
(5, 4),
(6, 3),
(7, 5),
(8, 2),
(9, 2),
(10, 1),
(11, 5),
(12, 5),
(1, 3),
(2, 2),
(3, 1),
(4, 2),
(5, 3),
(6, 5),
(7, 2),
(8, 1),
(9, 5),
(10, 3),
(11, 2),
(12, 2),
(1, 4),
(2, 2),
(3, 1),
(4, 5),
(5, 5),
(6, 4),
(7, 4),
(8, 5),
(9, 4),
(10, 1),
(11, 1),
(12, 5),
(1, 5),
(2, 2),
(3, 1),
(4, 5),
(5, 3),
(6, 3),
(7, 1),
(8, 3),
(9, 5),
(10, 1),
(11, 2),
(12, 2),
(1, 4),
(2, 4),
(3, 2),
(4, 4),
(5, 4),
(6, 4),
(7, 5),
(8, 4),
(9, 2),
(10, 2),
(11, 1),
(12, 3),
(1, 1),
(2, 3),
(3, 4),
(4, 2),
(5, 4),
(6, 2),
(7, 1),
(8, 4),
(9, 5),
(10, 3),
(11, 3),
(12, 2),
(1, 5),
(2, 3),
(3, 5),
(4, 3),
(5, 4),
(6, 4),
(7, 5),
(8, 5),
(9, 1),
(10, 3),
(11, 5),
(12, 1),
(1, 1),
(2, 4),
(3, 3),
(4, 3),
(5, 4),
(6, 2),
(7, 5),
(8, 3),
(9, 2),
(10, 1),
(11, 3),
(12, 2),
(1, 3),
(2, 1),
(3, 4),
(4, 3),
(5, 3),
(6, 1),
(7, 4),
(8, 5),
(9, 4),
(10, 1),
(11, 1),
(12, 1),
(1, 3),
(2, 5),
(3, 4),
(4, 3),
(5, 3),
(6, 5),
(7, 3),
(8, 1),
(9, 5),
(10, 1),
(11, 1),
(12, 3),
(1, 2),
(2, 4),
(3, 4),
(4, 3),
(5, 2),
(6, 5),
(7, 3),
(8, 2),
(9, 2),
(10, 3),
(11, 2),
(12, 4),
(1, 3),
(2, 2),
(3, 2),
(4, 5),
(5, 4),
(6, 3),
(7, 4),
(8, 5),
(9, 4),
(10, 4),
(11, 4),
(12, 5),
(1, 2),
(2, 5),
(3, 3),
(4, 2),
(5, 2),
(6, 4),
(7, 5),
(8, 3),
(9, 2),
(10, 3),
(11, 3),
(12, 2),
(1, 4),
(2, 1),
(3, 1),
(4, 3),
(5, 5),
(6, 3),
(7, 5),
(8, 4),
(9, 2),
(10, 1),
(11, 5),
(12, 4),
(1, 4),
(2, 5),
(3, 3),
(4, 3),
(5, 1),
(6, 4),
(7, 4),
(8, 4),
(9, 1),
(10, 4),
(11, 2),
(12, 4);

